### ISSUE TITLE
Add to benchmark?

### ISSUE THREAD

**Issue by proyb6** [cnotch/apirouter#1]
https://github.com/the-benchmarker/web-frameworks

When I seen Aero in that benchmark appeared to be less performant than httprouter, how about adding cnotch apirouter to the benchmark?

**Comment by cnotch** [comment]
https://github.com/cnotch/go-http-routing-benchmark

Aero and Apirouter each have their merits

**Comment by proyb6** [comment]
Yes, I have seen your benchmark and everywhere on GitHub, however, I mean to say if your router could participate in the Web frameworks benchmark which use Docker to compare how well it can perform as opposite to run on host machine.

**Comment by cnotch** [comment]
I haven't really noticed this project. I've been using Git for a short time, and I'm not familiar with how to collaborate on projects with other people.It should be easy to add if you are interested.

**Comment by waghanza** [comment]
If you mind @cnotch, I can help

**Comment by cnotch** [comment]
@waghanza , If so, thank you very much
